const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Home',
      items: ['kr/index'],  // KR 루트 README.md
    },
    {
      type: 'category',
      label: 'Intro',
      items: [{ type: 'autogenerated', dirName: 'kr/intro' }],
    },
    {
      type: 'category',
      label: 'Docs',
      items: [{ type: 'autogenerated', dirName: 'kr' }], // intro 포함 시 제외 처리 필요
    },
  ],
};

export default sidebars;
