const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Home',               // 루트 README.md
      items: ['index'],
    },
    {
      type: 'category',
      label: 'Intro',
      items: [{ type: 'autogenerated', dirName: 'intro' }], // docs/intro 폴더
    },
    {
      type: 'category',
      label: 'Docs',
      items: [{ type: 'autogenerated', dirName: '.' }],     // docs 폴더 전체, intro 제외
    },
  ],
};

export default sidebars;
