const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'docs',       // 상위 카테고리 이름
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs' // 하위는 자동
        },
      ],
    },
  ],
};

export default sidebars;
