const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Intro',
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro', // docs/intro/ 폴더를 자동으로 사이드바에 넣음
        },
      ],
    },
    {
      type: 'category',
      label: 'Docs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs', // docs/docs/ 폴더를 자동으로 사이드바에 넣음
        },
      ],
    },
  ],
};

export default sidebars;
