const sidebars = {
  // intro 전용 사이드바
  introSidebar: [
    {
      type: 'autogenerated',
      dirName: 'intro', // docs/intro/ 폴더 기준
    },
  ],

  // docs 전용 사이드바
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs', // docs/docs/ 폴더 기준
    },
  ],
};

export default sidebars;
