// pages/config/sidebars/sidebars_en.js
const sidebars = {
  // EN intro 전용 사이드바
  introSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // pages/en/intro 기준
    },
  ],

  // EN docs 전용 사이드바
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // pages/en/docs 기준
    },
  ],
};

export default sidebars;
