// pages/config/sidebars/sidebars_kr.js
const sidebars = {
  // KR intro 전용 사이드바
  introSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // pages/kr/intro 기준
    },
  ],

  // KR docs 전용 사이드바
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // pages/kr/docs 기준
    },
  ],
};

export default sidebars;
