-dontwarn javax.annotation.processing.**
-dontwarn com.google.auto.service.**

# Explicit rules generated by the Android Gradle plugin to suppress missing processor classes
-dontwarn javax.annotation.processing.AbstractProcessor
-dontwarn javax.annotation.processing.SupportedOptions