<<<<<<< HEAD
-dontwarn javax.annotation.processing.**
-dontwarn com.google.auto.service.**

# Explicit rules generated by the Android Gradle plugin to suppress missing processor classes
-dontwarn javax.annotation.processing.AbstractProcessor
-dontwarn javax.annotation.processing.SupportedOptions
=======
-dontwarn com.google.auto.service.**
-keep class com.google.auto.service.processor.AutoServiceProcessor { *; }
-keepclassmembers class com.google.auto.service.processor.AutoServiceProcessor { *; }
>>>>>>> refs/remotes/origin/main
