const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Home',
      items: ['en/index'], 
    },
    {
      type: 'category',
      label: 'Intro',
      items: [{ type: 'autogenerated', dirName: 'en/intro' }],
    },
    {
      type: 'category',
      label: 'Docs',
      items: [{
        type: 'autogenerated',
        dirName: 'en',
        exclude: ['en/intro/**'],
      }],
    },
  ],
};

export default sidebars;
