const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Intro',
      items: [
        'intro/index', // 첫 화면으로 명시적으로 추가!
        {
          type: 'autogenerated',
          dirName: 'intro',
        },
      ],
    },
    {
      type: 'category',
      label: 'Docs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs',
        },
      ],
    },
  ],
};

export default sidebars;
