const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Home',
      items: ['kr/index'],  // KR 루트 README.md
    },
    {
      type: 'category',
      label: 'Intro',
      items: [{ type: 'autogenerated', dirName: 'kr/intro' }],
    },
    {
      type: 'category',
      label: 'Docs',
      items: [{
        type: 'autogenerated',
        dirName: 'kr',
        exclude: ['kr/intro/**'], // "kr/intro" 디렉토리 전체를 제외
      }],
    },
  ],
};

export default sidebars;
